biblioteca/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('', RedirectView.as_view(url='/catalogo/')),
]

urlpatterns += [
    path('catalogo/', include('catalogo.urls')),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

catalogo/urls.py
import imp
from unicodedata import name
from django.urls import path
from catalogo import views

urlpatterns = [
  path('', views.index, name='index'),
  path('livros/', views.BookListView.as_view(), name='livros'),
  path('livros/<int:pk>', views.BookDetailView.as_view(), name='livro-detalhes'),
]

urlpatterns += [
    path('meusemprestimos/', views.LoanedBooksByUserListView.as_view(), name='meus-emprestimos'),
]

urlpatterns += [
    path('livro/<uuid:pk>/renovar/', views.renew_book, name='renovar-livro'),
]

urlpatterns += [
    path('autores/', views.AutorListView.as_view(), name='autores'),
    path('autores/<int:pk>', views.AutorDetailView.as_view(), name='autor-detalhes'),
    path('autor/create/', views.AutorCreate.as_view(), name='autor-create'),
    path('autor/<int:pk>/update/', views.AutorUpdate.as_view(), name='autor-update'),
    path('autor/<int:pk>/delete/', views.AutorDelete.as_view(), name='autor-delete'),
]

catalogo/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Genero(models.Model):
  
    nome = models.CharField(max_length=200, help_text='Entre com um gênero de livro. Ex: Ficção científica.')
    
    def __str__(self):
        return self.nome
      
class Linguaguem(models.Model):
  
    nome = models.CharField(max_length=200, help_text='Entre com a Linguagyem do Livro.')
    
    def __str__(self):
        return self.nome
      
class Autor(models.Model):
  
      primeiro_nome = models.CharField(max_length=100)
      ultimo_nome = models.CharField(max_length=100)
      data_nascimento = models.DateField(null=True, blank=True)
      data_falecimento = models.DateField(null=True, blank=True)
      
      class Meta:
        ordering = ['ultimo_nome', 'primeiro_nome']
        permissions = (("pode_manipular_autor", "Manipula o cadastro de autores."),)
        
      def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('autor-detalhes', args=[str(self.id)])
        
      def __str__(self):
        return f'{self.ultimo_nome}, {self.primeiro_nome}'
      
class Livro(models.Model):
  
      titulo = models.CharField(max_length=200)
      autor = models.ForeignKey(Autor, on_delete=models.SET_NULL, null=True)
      resumo = models.TextField(max_length=1000, help_text='Digite uma descrição do livro')
      isbn = models.ManyToManyField(Genero, help_text='Selecione um gênero para esse livro.')
      linguagem = models.ForeignKey(Linguaguem, on_delete=models.SET_NULL, null=True)
      
      def get_absolute_url(self):
          return reverse('livro-detalhes', args=[str(self.id)])
      
      def __str__(self):
        return self.titulo
      
import uuid
from django.contrib.auth.models import User
from datetime import date

class ExemplarLivro(models.Model):
  
  id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Identificar único para esse exemplar')
  livro = models.ForeignKey(Livro, on_delete=models.SET_NULL, null=True)
  editora = models.CharField(max_length=200)
  data_devolucao = models.DateField(null=True, blank=True)
  usuario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
  
  SITUACAO_EXEMPLAR = (
    ('m', 'Manutenção'),
    ('e', 'Emprestado'),
    ('d', 'Disponivel'),
    ('r', 'Reservado'),
  )
  
  situacao = models.CharField(
    max_length=1,
    choices=SITUACAO_EXEMPLAR,
    blank=True,
    default='m',
    help_text='Situação do Exemplar'
  )
  
  @property
  def esta_atrasado(self):
    if self.data_devolucao and date.today() > self.data_devolucao:
      return True
    return False
  
  class Meta:
    ordering = ['data_devolucao']
    permissions = (("pode_renovar_emprestimo", "Pode renovar empréstimo."),)
    
  def __str__(self):
    return f'{self.id} ({self.livro.titulo})'
      

catalogo/forms.py
from django import forms
import datetime
from django.core.exceptions import ValidationError

class RenovarLivroForm(forms.Form):
    data_renovacao = forms.DateField(help_text="Entre com uma data entre agora e 4 semanas (default 3).")

    def validar_data_renovacao(self):

        data = self.cleaned_data['data_renovacao']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError('Data inválida - renovação no passado.')

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError('Data inválida - renovação com mais de 4 semanas.')

        # Remember to always return the cleaned data.
        return data
        

catalogo/views.py
from django.shortcuts import render
from django.views import generic

# Create your views here.

from catalogo.models import Genero, Linguaguem, Autor, Livro, ExemplarLivro

def index(request):
  
    # contando o numero de livros e exemplares  
    num_livros = Livro.objects.all().count()
    num_exemplares = ExemplarLivro.objects.all().count()
    
    # Contando a quantidade de exemplares disponiveis (situacao = 'd')
    num_exemplares_disponiveis = ExemplarLivro.objects.filter(situacao__exact='d').count()
    
    # Contando o numero de autores. A opcao 'all()' é implicita por padrao
    num_autores = Autor.objects.count()
    
    num_visitas = request.session.get('num_visitas', 0)
    request.session['num_visitas'] = num_visitas + 1
    
    contexto = {
      'num_livros': num_livros,
      'num_exemplares': num_exemplares,
      'num_exemplares_disponiveis': num_exemplares_disponiveis,
      'num_autores': num_autores,
      'num_visitas': num_visitas,
    }
    
    # renderizando o template index.html com os dados da variavel contexto
    return render(request, 'index.html', context=contexto)
  
class BookListView(generic.ListView):
      
      model =  Livro
      
class BookDetailView(generic.DetailView):
      
      model = Livro
      
from django.contrib.auth.mixins import LoginRequiredMixin

class LoanedBooksByUserListView(LoginRequiredMixin,generic.ListView):

    model = ExemplarLivro
    template_name = 'catalogo/exemplares_emprestados_usuario.html'

    def get_queryset(self):
        return ExemplarLivro.objects.filter(usuario=self.request.user).filter(situacao__exact='e').order_by('data_devolucao')
      
import datetime
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import permission_required

from catalogo.forms import RenovarLivroForm


@permission_required('catalogo.pode_renovar_emprestimo')
def renew_book(request, pk):
    
    book_instance = get_object_or_404(ExemplarLivro, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenovarLivroForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_instance.data_devolucao = form.cleaned_data['data_renovacao']
            book_instance.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('meus-emprestimos') )

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenovarLivroForm(initial={'data_renovacao': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }

    return render(request, 'catalogo/renovar_livro.html', context)

class AutorListView(generic.ListView):

    model = Autor


class AutorDetailView(generic.DetailView):
    
    model = Autor


from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from django.contrib.auth.mixins import PermissionRequiredMixin

class AutorCreate(PermissionRequiredMixin, CreateView):
    
    permission_required = 'catalogo.pode_manipular_autor'
    model = Autor
    fields = '__all__'
    initial = {'data_falecimento': '05/01/2018'}

class AutorUpdate(PermissionRequiredMixin, UpdateView):
    
    permission_required = 'catalogo.pode_manipular_autor'
    model = Autor
    fields = ['primeiro_nome', 'ultimo_nome', 'data_nascimento', 'data_falecimento']

class AutorDelete(PermissionRequiredMixin, DeleteView):
    
    permission_required = 'catalogo.pode_manipular_autor'    
    model = Autor
    success_url = reverse_lazy('autores')

catalogo/templates/catalogo/autor_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Apagar Autor</h1>

<p>Tem certeza que quer excluir esse ator: {{ autor }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Sim, excluir.">
</form>

{% endblock %}

catalogo/templates/catalogo/autor_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Autor: {{ autor.ultimo_nome }}, {{ autor.primeiro_nome }}</h1>

<p><strong>Primeiro nome: </strong>{{ autor.primeiro_nome }}</a></p>
<p><strong>Último nome:</strong> {{ autor.ultimo_nome }}</p>
<p><strong>Data de nascimento</strong> {{ autor.data_nascimento }}</p>
<p><strong>Data de falecimento:</strong> {{ autor.data_falecimento }}</p>

{% endblock %}

catalogo/templates/catalogo/autor_form.html
{% extends "base_generic.html" %}

{% block content %}
<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit">
</form>
{% endblock %}

catalogo/templates/catalogo/autor_list.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Lista de Autores</h1>

{% if perms.catalogo.pode_manipular_autor %}
<a href="{% url 'autor-create' %}"> Novo autor</a>
{% endif %}

{% if autor_list %}
<ul>
  {% for autor in autor_list %}
  <li>
    <a href="{{ autor.get_absolute_url }}">{{ autor.ultimo_nome }}, {{ autor.primeiro_nome }}</a>
    {% if perms.catalogo.pode_manipular_autor %}
    <a href="{% url 'autor-update' autor.id%}"> - Atualizar</a>
    <a href="{% url 'autor-delete' autor.id%}"> - Excluir</a>
    {% endif %}
  </li>
  {% endfor %}
</ul>

{% else %}
<p>Não existem autores cadastrados.</p>
{% endif %}

{% endblock %}

catalogo/templates/catalogo/exemplares_emprestados_usuario.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Livros Emprestados</h1>

{% if exemplarlivro_list %}
<ul>

  {% for exemplarlivro in exemplarlivro_list %}
  <li class="{% if exemplarlivro.esta_atrasado %}text-danger{% endif %}">
    <a href="{% url 'livro-detalhes' exemplarlivro.livro.pk %}">{{exemplarlivro.livro.titulo}}</a> ({{ exemplarlivro.data_devolucao }})
    {% if perms.catalogo.pode_renovar_emprestimo %}
    <a href="{% url 'renovar-livro' exemplarlivro.id %}"> - Renovar</a>
    {% endif %}
  </li>
  {% endfor %}
</ul>

{% else %}
<p>Não há livros emprestados para você.</p>
{% endif %}
{% endblock %}

catalogo/templates/catalogo/livro_detail.html
<!--extendendo-->
{% extends "base_generic.html" %}

{% block content %}
<h1>Título: {{ livro.titulo }}</h1>

<!--Representando as entidades-->
<p><strong>Autor:</strong> <a href="">{{ livro.autor }}</a></p> <!-- author detail link not yet defined -->
<p><strong>Resumo:</strong> {{ livro.resumo }}</p>
<p><strong>ISBN:</strong> {{ livro.isbn }}</p>
<p><strong>Linguagem:</strong> {{ livro.linguagem }}</p>
<p><strong>Gênero:</strong>
  {% for genero in livro.genero.all %}
  {{ genero }}
  {% if not forloop.last %}
  ,
  {% endif %}
  {% endfor %}</p>

<div style="margin-left:20px;margin-top:20px">
  <h4>Exemplares</h4>

  {% for copy in livro.exemplarlivro_set.all %}
  <hr>
  <p class="
                {% if copy.situacao == 'd' %}
                    text-success
                {% elif copy.situacao == 'm' %}
                    text-danger
                {% else %}text-warning{% endif %}">

    {{ copy.get_situacao_display }}</p>

  {% if copy.situacao != 'd' %}
  <p><strong>Deve ser devolvido em:</strong> {{copy.data_devolucao}}</p>
  {% endif %}

  <p><strong>Editora:</strong> {{copy.editora}}</p>
  <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
  {% endfor %}

</div>
{% endblock %}

catalogo/templates/catalogo/livro_list.html
{% extends "base_generic.html" %}

<!--inicio bloco-->
{% block content %}

{% if livro_list %}
<h1>Lista de Livros</h1>
<ul>
  <!--comando for-->
  {% for livro in livro_list %}
  <li>
    <a href="{{ livro.get_absolute_url }}">
      {{livro.titulo}}
    </a>
    {{livro.autor}}
  </li>
  {% endfor %}
</ul>
{% else %}
<p>Não existem livros na biblioteca</p>
{% endif %}
{% endblock %}
<!--fim bloco-->

catalogo/templates/catalogo/renovar_livro.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Renovar: {{ book_instance.Livro.titulo }}</h1>
<p>Usuário: {{ book_instance.usuario }}</p>
<p {% if book_instance.esta_atrasado %} class="text-danger" {% endif %}>Data de devolução: {{ book_instance.data_devolucao }}</p>

<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit">
</form>
{% endblock %}